name: Playwright CI + Pages

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  test:
    name: Run Playwright tests (Chromium, HTML + JUnit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright (Chromium only)
        run: npx playwright install --with-deps chromium

      # Reporters are configured in playwright.config.ts (HTML + list + JUnit if you added it there)
      - name: Run tests (Chromium only)
        run: npx playwright test tests/e2e.parabank.spec.ts --project=chromium
        env:
          BASE_URL: https://parabank.parasoft.com
          FALLBACK_TO_ACCOUNT: ${{ secrets.FALLBACK_TO_ACCOUNT || '12345' }}
          # Optional: needed if you use SecureStore in CI
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Upload HTML report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload JUnit report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.xml

      - name: Upload Pages artifact (HTML report)
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

  deploy:
    name: Publish HTML report to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
