name: Playwright CI + Pages

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  test:
    name: Run Playwright tests (HTML + JUnit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run only your E2E flow on Chromium in headless mode (default on CI)
      # Also emit JUnit so the upload step has a file to grab.
      - name: Run tests
        run: npx playwright test tests/e2e.parabank.spec.ts --project=chromium --reporter=html,junit
        env:
          BASE_URL: https://parabank.parasoft.com
          # If you store a real value in repo Secrets, it will override the default:
          FALLBACK_TO_ACCOUNT: ${{ secrets.FALLBACK_TO_ACCOUNT }}
          # SECRET_KEY only matters if tests touch SecureStore; harmless if unset.
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Upload HTML report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload JUnit report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.xml
          if-no-files-found: ignore

      - name: Upload Pages artifact (HTML report)
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

  deploy:
    name: Publish HTML report to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    if: always() # publish even if tests fail
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
