name: Playwright CI + Pages

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  test:
    name: Run Playwright tests (HTML + JUnit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 👇 No --reporter here; reporters are configured in playwright.config.ts
      - name: Run tests
        run: npx playwright test
        env:
          BASE_URL: https://parabank.parasoft.com
          FALLBACK_TO_ACCOUNT: ${{ secrets.FALLBACK_TO_ACCOUNT || '12345' }}

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload JUnit report artifact
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.xml

      - name: Upload Pages artifact (HTML report)
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

  deploy:
    name: Publish HTML report to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }} # publish even if tests fail
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
